version: v1.0
name: Deployment to prod
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: "Execute on master"
    task:
      secrets:
        - name: helpscout-docs

      jobs:
        - name: Deploy
          commands:
            - checkout
            - gem install redcarpet
            - ./deploy_docs.rb
